version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
  
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
